export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_LESSON_INFO = 'FETCH_LESSON_INFO';
export const FETCH_USER_INFO_SUC = 'FETCH_USER_INFO_SUC';
export const FETCH_LESSON_INFO_SUC = 'FETCH_LESSON_INFO_SUC';
export const FETCH_USER_INFO_FAI = 'FETCH_USER_INFO_FAI';
export const FETCH_LESSON_INFO_FAI = 'FETCH_USER_INFO_FAI';


export const FETCH_PROFILE_INFO = 'FETCH_PROFILE_INFO';
export const FETCH_PROFILE_INFO_SUC = 'FETCH_PROFILE_INFO_SUC';
export const FETCH_PROFILE_INFO_FAI = 'FETCH_PROFILE_INFO_FAI';


export const FETCH_SATISFILED_INFO = 'FETCH_SATISFILED_INFO';
export const FETCH_SATISFILED_INFO_SUC = 'FETCH_SATISFILED_INFO_SUC';
export const FETCH_SATISFILED_INFO_FAI = 'FETCH_SATISFILED_INFO_FAI';


export const FETCH_CLASS_INFO = 'FETCH_CLASS_INFO';
export const FETCH_CLASS_INFO_SUC = 'FETCH_CLASS_INFO_SUC';
export const FETCH_CLASS_INFO_FAI = 'FETCH_CLASS_INFO_FAI';


export const FETCH_MYWILLREVIEW_HOMEWORK_INFO = 'FETCH_MYWILLREVIEW_HOMEWORK_INFO';
export const FETCH_ALLWILLREVIEW_HOMEWORK_INFO = 'FETCH_ALLWILLREVIEW_HOMEWORK_INFO';
export const FETCH_MYREVIEWED_HOMEWORK_INFO = 'FETCH_MYREVIEWED_HOMEWORK_INFO';
export const FETCH_ALLREVIEWED_HOMEWORK_INFO = 'FETCH_ALLREVIEWED_HOMEWORK_INFO';

export const SELECTBYMID = 'SELECTBYMID'
export const SELECTBYNICK = 'SELECTBYNICK'

export const CHANGEREPLYSTATUS = 'CHANGEREPLYSTATUS'

