export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_LESSON_INFO = 'FETCH_LESSON_INFO';
// export const STORE_USER_INFO = 'STORE_USER_INFO';
// export const STORE_LESSON_INFO = 'STORE_LESSON_INFO';
export const FETCH_USER_INFO_SUC = 'FETCH_USER_INFO_SUC';
export const FETCH_LESSON_INFO_SUC = 'FETCH_LESSON_INFO_SUC';
export const FETCH_USER_INFO_FAI = 'FETCH_USER_INFO_FAI';
export const FETCH_LESSON_INFO_FAI = 'FETCH_USER_INFO_FAI';
